### PR TITLE
Adding Hover Effect in places on each cards 

### PR DESCRIPTION
**Pull request by anuukriti**

### CODE REVIEW

**Comment by sameer-soni** [comment]
@anuukriti  can you also add this on the card of 'Explore' page

**Comment by anuukriti** [comment]
> @anuukriti can you also add this on the card of 'Explore' p

**Comment by anuukriti** [comment]
> > @anuukriti can you also add this on the card of 'Explore' p

okay

**Comment by anuukriti** [comment]
> > @anuukriti can you also add this on the card of 'Explore' p

I added the hover effect for each card in the explore section.

**Comment by sameer-soni** [comment]
@anuukriti can you solve the conflicts? I'll merge your pr then.

**Comment by anuukriti** [comment]
> @anuukriti can you solve the conflicts? I'll merge your pr then.

I solved the conflicts but what's the problem with Vercel, can you please explain me, I am beginner for  open source contribution

**Comment by sameer-soni** [comment]
@anuukriti there may be some kind of error in your code due to that vercel deployment is getting failed.

**Pull request closed without merging**
