### PR TITLE
Added the reponsive ness in the website 

### PR DESCRIPTION
**Pull request by suraj-9849**
Issue : #54 #23 

Added the responsive ness in the whole website

### CODE REVIEW

**Comment by Omkar-Sonawane-23** [comment]
Not Working.

**Comment by suraj-9849** [comment]
Can u please tell me where it is not working @Omkar-Sonawane-23 i can see everything is working fine

**Comment by Omkar-Sonawane-23** [comment]
image

**Comment by suraj-9849** [comment]
but u told to keep the previous code of navbar and home page so I kept the same. and it is like that only so thats the reason I made them responsive before itself but  u told keep the previous if u tell me to make it responsive then I will make it @Omkar-Sonawane-23

**Pull request closed without merging**
