### PR TITLE
changes the UI of explore page, Now there is a slideshow of backgroun…

### PR DESCRIPTION
**Pull request by devu007**
I have added a slideshow of images in the background of the explore page, it improves the UI of the page and hence it looks attractive.

### CODE REVIEW

**Comment by sameer-soni** [comment]
@devu007 slideshow is good but the old UI was better.

**Comment by devu007** [comment]
Okay how about I change the select box?

**Comment by sameer-soni** [comment]
@devu007 you can add the background slideshow, add good quality images not of lower resolution

**Comment by devu007** [comment]
Okay sure, can I use images from other sources as of now I am using images from data.json file.

**Comment by sameer-soni** [comment]
> Okay sure, can I use images from other sources as of now I am using images from data.json file.

sure you can.

**Comment by devu007** [comment]
I have made the changes, How can I resolve the conflict now as I am not able to merge with Dev branch

**Comment by devu007** [comment]
Hey @sameer-soni can you please review the changes that I have made.

**Pull request merged**
