### PR TITLE
Added the Responsiveness in the Homeque.jsx and also in the Home.jsx

### PR DESCRIPTION
**Pull request by suraj-9849**
Issue: #23 

I made the changes in the Homeque.jsx and also in the Home,jsx by adding the responsive ness using the tailwind. also made the changes in the cards added the hover effect

### CODE REVIEW

**Comment by Omkar-Sonawane-23** [comment]
Not Working Properly

**Comment by suraj-9849** [comment]
What can u please tell me the issue

**Comment by suraj-9849** [comment]
I will try to sort it out please don't close this issue I spent lot of time to enhance it website

**Comment by suraj-9849** [comment]
@Omkar-Sonawane-23  can u please tell me the issue I will try to sort it out please

**Comment by suraj-9849** [comment]
https://github.com/Omkar-Sonawane-23/Tourism/assets/146669517/2a5133b5-50be-4a34-baeb-33a4ffe3c45b

**Comment by Omkar-Sonawane-23** [comment]
Make a PR Without any Changes In Hompage and Navbar.

**Comment by sameer-soni** [comment]
@suraj-9849 It's responsive in mobile view but in desktop view, you have changed the view. Keep it at it is originally and make it responsive, don't change it's look in desktop view.

**Comment by suraj-9849** [comment]
Before:

https://github.com/Omkar-Sonawane-23/Tourism/assets/146669517/1881ff5e-6340-4546-99d6-4b9c620dfc61

After:
https://github.com/Omkar-Sonawane-23/Tourism/assets/146669517/ceb66bfd-ffea-4e9c-9f75-787cd41b0357

@sameer-soni is this ok if yes then I will make the PR

**Comment by suraj-9849** [comment]
image
 this is the website view

**Comment by suraj-9849** [comment]
@sameer-soni So I made every thing if everything is ok then I will make the PR on the DEV branch

**Comment by sameer-soni** [comment]
@suraj-9849 yes, it's looking good now. I'm closing this pr, you make a new one and then I'll merge it.

**Pull request closed without merging**
