### PR TITLE
Issue269-Added pagination in Places Page

### PR DESCRIPTION
**Pull request by ANSH127**
Displaying 9 places per page and pagination will automatically adjust itself if number  of the places dataset is large
 
https://github.com/Omkar-Sonawane-23/Tourism/assets/119344874/d43036ac-d3a2-4dbd-97ca-c1c74c70ee3c

### CODE REVIEW

**Comment by ANSH127** [comment]
changing back to  top button color similar to the scrollbar and pagination container

Screenshot (209)

**Comment by ANSH127** [comment]
@sameer-soni  brother kindly give difficulty level also it will beneficial in my PR points

**Comment by sameer-soni** [comment]
@ANSH127 I keep forgetting it, sorry though.

**Comment by ANSH127** [comment]
@sameer-soni Np Brother :)

**Pull request merged**
