### PR TITLE
Added the Responsive ness in the Whole website

### PR DESCRIPTION
**Pull request by suraj-9849**
Issue : #54 #23 
I have added the responsive ness in the whole website and also changed the cards @sameer-soni

### CODE REVIEW

**Comment by sameer-soni** [comment]
@suraj-9849 you have pushed the node_modules folder.

**Comment by suraj-9849** [comment]
Oh ok I will do it

**Comment by suraj-9849** [comment]
Yeah I removed it from the gitignore file and made the PR is it ok now @sameer-soni

**Comment by suraj-9849** [comment]
And there is no label to this issue can you please add the level label please @sameer-soni

**Comment by sameer-soni** [comment]
@suraj-9849 again, you have pushed node modules folder, you didnt have to remove i from .gitignore, you have to add node_modules so it'll get ignored and won't get pushed.

**Comment by suraj-9849** [comment]
Sir how to do it sir can you please tell me I again clone the repo and made the changes and while pushing there is no sign that it is being added. please help me @sameer-soni (sign meant the green dot )

**Comment by suraj-9849** [comment]
@sameer-soni, I Pushed the Node modules folder now you can check

**Comment by suraj-9849** [comment]
@sameer-soni Can you please add the label of level to this.

**Comment by suraj-9849** [comment]
@sameer-soni  the commands which you told I executed them in the terminal now is this ok

**Comment by sameer-soni** [comment]
@suraj-9849 👍

**Comment by suraj-9849** [comment]
@sameer-soni add some level label bro like level1,level2

**Pull request merged**
