### PR TITLE
Fix/issue 11 about page added

### PR DESCRIPTION
**Pull request by SnehansuBehera**
About page added and made responsive with About Us in navbar rendering done

### CODE REVIEW

**Comment by sameer-soni** [comment]
@SnehansuBehera  nice work with explore and about us page, but it's not responsive. "Places" page is updated, so can you just implement the about us page and explore page in the updated repo.

**Comment by SnehansuBehera** [comment]
@sameer-soni can we talk else where in detail what you exactly want me to do??

**Comment by sameer-soni** [comment]
@SnehansuBehera You can join the discord server [discord](https://discord.gg/uD7x8Mah). What I meant was, we have updated the 'Places' page UI, so I want to use that UI instead of yours. So, can you make another commit in which you have only implemented the 'Explore' and 'About' page.

**Comment by SnehansuBehera** [comment]
okay @sameer-soni

**Comment by SnehansuBehera** [comment]
@sameer-soni i just closed the pr and i have taken your all changes into my local repo with yours updated places section and now i am working on the explore & about us page from whole new forked repo and i will make the pr asap

**Pull request closed without merging**
